/**
 * Built-in Generation Presets
 *
 * Each preset is tuned for a specific use case. The values reflect
 * real-world testing against FLUX and SDXL checkpoints.
 *
 * Design principles:
 * - Presets are data, not code — plain objects, fully serializable
 * - Every field is tested against the encoder to avoid wasted tokens
 * - Negatives target each domain's most common failure modes
 */

import type { GenerationPreset } from './types.js';

export const BUILT_IN_PRESETS: GenerationPreset[] = [
  {
    id: 'tech-startup',
    name: 'Tech Startup',
    description: 'Geometric, clean lines — optimized for tech companies and developer tools',
    category: 'industry',
    style: 'geometric',
    logoType: 'symbol',
    composition: 'centered',
    checkpoint: 'flux1-dev.safetensors',
    model: 'black-forest-labs/FLUX.1-Dev',
    sampler: 'euler',
    scheduler: 'simple',
    cfg: 3.5,
    steps: 30,
    width: 1024,
    height: 1024,
    extraNegatives: ['organic', 'hand drawn', 'watercolor', 'vintage', 'ornate'],
  },
  {
    id: 'luxury-brand',
    name: 'Luxury Brand',
    description: 'Elegant metallic finish — refined materials, premium feel',
    category: 'industry',
    style: 'elegant',
    logoType: 'combination',
    composition: 'centered',
    checkpoint: 'sdxl_base_1.0.safetensors',
    model: 'black-forest-labs/FLUX.2-pro',
    sampler: 'dpmpp_2m',
    scheduler: 'karras',
    cfg: 7.0,
    steps: 30,
    width: 1024,
    height: 1024,
    extraNegatives: ['cheap', 'clip art', 'cartoon', 'childish', 'neon', 'loud'],
  },
  {
    id: 'gaming',
    name: 'Gaming',
    description: 'Bold, dynamic energy — aggressive shapes and high contrast',
    category: 'industry',
    style: 'brutalist',
    logoType: 'symbol',
    composition: 'centered',
    checkpoint: 'flux1-schnell.safetensors',
    model: 'black-forest-labs/FLUX.1-schnell',
    sampler: 'euler',
    scheduler: 'simple',
    cfg: 1.0,
    steps: 4,
    width: 1024,
    height: 1024,
    extraNegatives: ['corporate', 'delicate', 'pastel', 'thin lines', 'calming'],
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    description: 'Organic, calming forms — professional and trustworthy',
    category: 'industry',
    style: 'organic',
    logoType: 'symbol',
    composition: 'centered',
    checkpoint: 'flux1-dev.safetensors',
    model: 'black-forest-labs/FLUX.1-Dev',
    sampler: 'euler',
    scheduler: 'simple',
    cfg: 3.5,
    steps: 30,
    width: 1024,
    height: 1024,
    extraNegatives: ['aggressive', 'sharp edges', 'dark', 'gothic', 'angular'],
  },
  {
    id: 'fintech',
    name: 'Fintech',
    description: 'Swiss precision — corporate, structured, trustworthy',
    category: 'industry',
    style: 'swiss',
    logoType: 'lettermark',
    composition: 'centered',
    checkpoint: 'sdxl_base_1.0.safetensors',
    model: 'black-forest-labs/FLUX.1-Dev',
    sampler: 'dpmpp_2m',
    scheduler: 'karras',
    cfg: 7.0,
    steps: 30,
    width: 1024,
    height: 1024,
    extraNegatives: ['playful', 'organic', 'hand drawn', 'casual', 'rounded'],
  },
  {
    id: 'creative-agency',
    name: 'Creative Agency',
    description: 'Expressive and modern — distinctive without being loud',
    category: 'industry',
    style: 'playful',
    logoType: 'combination',
    composition: 'centered',
    checkpoint: 'flux1-dev.safetensors',
    model: 'black-forest-labs/FLUX.2-pro',
    sampler: 'euler',
    scheduler: 'simple',
    cfg: 3.5,
    steps: 30,
    width: 1024,
    height: 1024,
    extraNegatives: ['corporate', 'rigid', 'formal', 'stiff', 'boring'],
  },
  {
    id: 'saas',
    name: 'SaaS',
    description: 'Minimal with gradient — clean, scalable, modern software feel',
    category: 'industry',
    style: 'minimal',
    logoType: 'wordmark',
    composition: 'horizontal',
    checkpoint: 'flux1-dev.safetensors',
    model: 'black-forest-labs/FLUX.1-Dev',
    sampler: 'euler',
    scheduler: 'simple',
    cfg: 3.5,
    steps: 30,
    width: 1024,
    height: 1024,
    extraNegatives: ['ornate', 'vintage', 'heavy', 'detailed', 'busy'],
  },
  {
    id: 'e-commerce',
    name: 'E-Commerce',
    description: 'Friendly and approachable — warm, inviting, colorful',
    category: 'industry',
    style: 'playful',
    logoType: 'combination',
    composition: 'centered',
    checkpoint: 'flux1-dev.safetensors',
    model: 'black-forest-labs/FLUX.1-Dev',
    sampler: 'euler',
    scheduler: 'simple',
    cfg: 3.5,
    steps: 25,
    width: 1024,
    height: 1024,
    extraNegatives: ['corporate', 'minimal', 'monochrome', 'stark', 'cold'],
  },
];
